# Establish default directories that all loaded configs can access,
# mainly for program locations
export HOME_DIR=("")
export PERSONAL_DIR=("")
export WORK_DIR=("")

# Load all our lovely nested config files
export _SETUP_CONFIG_PATH=($HOME_DIR/.autogen-config)
export _PERSONAL_CONFIG_PATH=($WORK_DIR/Z.files/zsh)
export _WORK_CONFIG_PATH=($PERSONAL_DIR/D.files/)

for config (
  # Autogenerated configs used by various utilities, 
  # such as p10k, npm, ...
  $_SETUP_CONFIG_PATH/*.zsh
  
  # Personal configs and utilities, like git shortcuts,
  # TuningFork settings, ...
  $_PERSONAL_CONFIG_PATH/*.zsh 

  # Bespoke work-related configs, likely containing credentials
  # and other nonsense that should not be committed to version control
  $_WORK_CONFIG_PATH/*.zsh
) source $config