alias c="/Users/zackamiton/Code/"
alias s="/Users/zackamiton/Code/BrownCS"
alias site="/Users/zackamiton/Code/Zamiton/webapp"
alias cla="/Users/zackamiton/Library/LaunchAgents/"
alias cld="/Library/LaunchDaemons/"